import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";

import GoTop from "@/components/GoTop";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Slideshow from "@/components/Slideshow";
import BrandList from "@/components/BrandList";
import ProductList from "@/components/ProductList";
import Pagination from "@/components/Pagination";
import SlideProduct from "@/components/SlideProduct";
import FilterSide from "@/components/FilterSide";

export default function Collection() {
  const [isOpen, setIsOpen] = useState(false);

  const handleClose = () => {
    setIsOpen(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />
      <SlideProduct />
      <div className="flex relative z-10 items-center overflow-hidden bg-white">
        <div className="flex justify-between items-center mx-auto pt-3 w-full px-4 md:px-0 md:w-11/12">
          <div className="rounded-full border-black w-[150px] md:w-[280px] border-2 border-solid hover:shadow-md transform duration-200 hover:scale-105">
            <button
              className="filter2 place-content-center flex w-full justify-between px-3 items-center py-1 text-black focus:outline-none "
              type="button"
              onClick={() => setIsOpen(!isOpen)}
            >
              <span className="text-black block max-w-[23ch] truncate text-14 font-semibold xs:max-w-none xs:text-16">
                Filter
              </span>
              <div>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M10.5 6h9.75M10.5 6a1.5 1.5 0 11-3 0m3 0a1.5 1.5 0 10-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-9.75 0h9.75"
                  />
                </svg>
              </div>
            </button>
          </div>
          <div className="w-[150px] md:w-[280px] py-3 flex flex-wrap md:flex-nowrap items-center">
            <select className="input-select text-sm z-1 border border-gray-800 text-black block truncate text-14 font-semibold">
              <option value="RANK_ASC">Popularity</option>
              <option value="PRICE_ASC">Lowest price</option>
              <option value="PRICE_DESC">Highest price</option>
              <option value="PRICE_DROP_ASC">Price drop</option>
              <option value="RATING_DESC">Rating</option>
              <option value="TREND_ASC">Trend</option>
              <option value="NAME_ASC">Name</option>
            </select>
          </div>
        </div>
      </div>
      <ProductList />
      <Pagination />
      <FilterSide
        isOpen={isOpen}
        handleClose={handleClose}
        setIsOpen={setIsOpen}
      />
      <Footer />
    </>
  );
}
