import React from 'react'
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import GoTop from '@/components/GoTop'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export default function Category() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />  
      <GoTop />

      <Footer />
    </>
  )
}
