import React from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import GoTop from "@/components/GoTop";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className="max-w-screen-xl mt-0 px-8 grid gap-8 grid-cols-1 md:grid-cols-2 md:px-12 lg:px-16 xl:px-32 py-16 mx-auto bg-[#f8f3e7] text-gray-900 rounded-lg shadow-lg">
        <div className="flex flex-col space-y-4">
          <div className="flex flex-col space-y-3">
            <h2 className="text-4xl lg:text-5xl font-bold leading-tight">
              Contact us{" "}
            </h2>
            <div className="text-lg text-gray-700 font-semibold">
              We always love to hear from you!
            </div>
            <span>
              Get in touch with any questions, thoughts or comments or simply if
              you want a chat and one of the team will be back in touch.
            </span>
          </div>
          <div className="flex flex-col space-y-0">
            <div>hello@beonhand.co.uk</div>
            <span>0203 488 2912</span>
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <div>
            <span className="text-md text-gray-600 font-semibold">
              Full Name
            </span>
            <input
              className="w-full bg-white border border-gray-400 text-gray-900 mt-2 p-3 rounded focus:outline-none focus:shadow-outline"
              type="text"
              placeholder=""
            />
          </div>
          <div className="">
            <span className="text-md text-gray-600 font-semibold">Email</span>
            <input
              className="w-full bg-white border border-gray-400 text-gray-900 mt-2 p-3 rounded focus:outline-none focus:shadow-outline"
              type="text"
            />
          </div>
          <div className="">
            <span className="text-md text-gray-600 font-semibold">Message</span>
            <textarea className="w-full h-32 bg-white border border-gray-400 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"></textarea>
          </div>
          <div className="">
            <button className="text-md font-bold tracking-wide bg-[#073d30] hover:opacity-80 text-white p-2 rounded-lg w-full focus:outline-none focus:shadow-outline">
              Send
            </button>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}
