import React from 'react'
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import FooterRegistration from "@/components/FooterRegistration";
import HeaderRegistration from "@/components/HeaderRegistration";
import ProfileNav from "@/components/ProfileNav";

export default function Orders() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderRegistration />

      <main className="bg-white min-h-screen">
        <ProfileNav />

        <div className="py-3 mx-auto w-11/12 ">
          <div className="flex w-full flex-col space-y-2">
            
            <div className="pt-5">
              <span className="text-lg font-bold tracking-tighter uppercase text-gray-800">
                Orders
              </span>
            </div>
            <div className="overflow-x-auto py-4 ">
              <table className="min-w-full text-sm">
                <thead className="bg-[#dde6ed] dark:bg-gray-700">
                  <tr className="text-left">
                    <th className="p-2">
                      <p>Date ordered</p>
                    </th>
                    <th className="p-2">
                      <p>Order ID</p>
                    </th>
                    <th className="p-2">
                      <p>Value</p>
                    </th>
                    <th className="p-2">
                      <p>Order Detail</p>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="bg-white text-gray-800 border-b font-bold border-opacity-20 dark:border-gray-700 dark:bg-gray-900">
                    <td className="p-2">
                      <p>Date ordered</p>
                    </td>
                    <td className="p-2">
                      <p>Order ID</p>
                    </td>
                    <td className="p-2">
                      <p>Value</p>
                    </td>
                    <td className="p-2">
                      <p>Order Detail</p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        </main>
    </>
  )
}
