import React from 'react'
import Head from "next/head";
import Image from 'next/image';
import Link from 'next/link';

import GoTop from '@/components/GoTop'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Slideshow from '@/components/Slideshow';
import BrandList from '@/components/BrandList';
import ProductList from '@/components/ProductList';

import promo from "@/assets/promo2.jpeg"
import bird from "@/assets/img/shopbypet-holiday-bird.png"
import cat from "@/assets/img/shopbypet-holiday-cat.png"
import dog from "@/assets/img/shopbypet-holiday-dog.png"
import fish from "@/assets/img/shopbypet-holiday-fish.png"
import reptile from "@/assets/img/shopbypet-holiday-reptile.png"
import smallpet from "@/assets/img/shopbypet-holiday-smallpet.png"


export default function Shop() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />  
      <GoTop />
      <Slideshow />
      <BrandList />
      <div>
        <Image src={promo} alt='' />
      </div>
      <div className="h-max mx-auto w-full lg:w-1/2 flex flex-col space-y-3 px-3 md:px-6 lg:px-0 py-0 md:py-4 justify-center2 items-center2 bg-white">
        <div>
          <span className="text-lg md:text-2xl font-bold text-[#002f6c]">Shop By Pets</span>
        </div>
        <div className="grid grid-cols-3 md:grid-cols-6 gap-3 mx-auto w-full md:w-12/12 items-center">
        <Link href={"/collection"} className="flex flex-col transform duration-200 hover:scale-105 justify-center items-center space-y-1 py-2 border-b-2 border-white hover:border-gray-900">
          <Image src={cat} className='w-28 ' alt='' />
          <div>
            <span className='font-semibold'>Cat</span>
          </div>
        </Link>
        <Link href={"/collection"} className="flex flex-col transform duration-200 hover:scale-105 justify-center items-center space-y-1 py-2 border-b-2 border-white hover:border-gray-900">
          <Image src={dog} className='w-28' alt='' />
          <div>
            <span className='font-semibold'>Dog</span>
          </div>
        </Link>
        <Link href={"/collection"} className="flex flex-col transform duration-200 hover:scale-105 justify-center items-center space-y-1 py-2 border-b-2 border-white hover:border-gray-900">
          <Image src={bird} className='w-28' alt='' />
          <div>
            <span className='font-semibold'>Bird</span>
          </div>
        </Link>
        <Link href={"/collection"} className="flex flex-col transform duration-200 hover:scale-105 justify-center items-center space-y-1 py-2 border-b-2 border-white hover:border-gray-900">
          <Image src={fish} className='w-28' alt='' />
          <div>
            <span className='font-semibold'>Fish</span>
          </div>
        </Link>
        <Link href={"/collection"} className="flex flex-col transform duration-200 hover:scale-105 justify-center items-center space-y-1 py-2 border-b-2 border-white hover:border-gray-900">
          <Image src={reptile} className='w-28' alt='' />
          <div>
            <span className='font-semibold'>Reptile</span>
          </div>
        </Link>
        <Link href={"/collection"} className="flex flex-col transform duration-200 hover:scale-105 justify-center items-center space-y-1 py-2 border-b-2 border-white hover:border-gray-900">
          <Image src={smallpet} className='w-28' alt='' />
          <div>
            <span className='font-semibold'>Small Pet</span>
          </div>
        </Link>
      </div>
      </div>
      <ProductList />
      <Footer />
    </>
  )
}
