import React from 'react'
import Head from "next/head";
import Image from 'next/image';

import GoTop from '@/components/GoTop'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Slideshow from '@/components/Slideshow';
import BrandList from '@/components/BrandList';
import ProductList from '@/components/ProductList';

import promo from "@/assets/promo2.jpeg"

export default function Shop() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />  
      <GoTop />
      <Slideshow />
      <BrandList />
      <div>
        <Image src={promo} alt='' />
      </div>
      <ProductList />
      <Footer />
    </>
  )
}
