import React from 'react'
import Head from "next/head";
import Image from "next/image";

import GoTop from "@/components/GoTop";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import detail from "@/assets/product/detail.png"
import detail1 from "@/assets/product/detail1.png"
import detail2 from "@/assets/product/detail2.png"
import detail3 from "@/assets/product/detail3.png"
import Ingredient from '@/components/Ingredient';
import Info from '@/components/Info';
import Popular from '@/components/Popular';

export default function Detail() {
  return (
    <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className='flex relative z-10 items-center overflow-hidden bg-white'>
        <div className='flex w-full'>
          <div className='w-1/2 bg-white'>
            <div className='flex justify-center items-center'>
              <Image src={detail1} alt='' />
            </div>
          </div>
          <div className='w-1/2 flex flex-col px-8 py-4 bg-[#f1f1f3]'>
            <div>
            <nav className="text-sm my-1" aria-label="Breadcrumb">
                  <ol className="list-none p-0 inline-flex">
                    <li className="flex items-center">
                      <a
                        href="#"
                        className="capitalize text-gray-900 hover:underline"
                      >
                        Product
                      </a>
                      <svg
                        className="fill-current text-gray-900 w-2 h-2 mx-1"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 320 512"
                      >
                        <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z" />
                      </svg>
                    </li>
                    <li className="flex items-center">
                      <a
                        href="#"
                        className="text-gray-900 capitalize hover:underline"
                        aria-current="page"
                      >
                        Treats
                      </a>
                      <svg
                        className="fill-current text-gray-900 w-2 h-2 mx-1"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 320 512"
                      >
                        <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z" />
                      </svg>
                    </li>
                    <li >
                      <a
                        href="#"
                        className="text-gray-900 font-semibold capitalize hover:underline"
                        aria-current="page"
                      >
                        Salmon Savory Chews
                      </a>
                      
                    </li>
                  </ol>
                </nav>
            </div>
            <div className='flex flex-col py-4 space-y-3'>
              <div>
                <span className='text-3xl font-semibold'>Salmon Savory Chews</span>
              </div>
              <div>
                <span className='text-lg'>$8.50</span>
              </div>
              <div>
                <span className='text-[17px]'>Spoil your cat with confidence, courtesy of our simple jerky treats. Kitty will love the big meaty flavor and chewy texture, and you’ll feel good knowing that they’re free from grains, fillers, and artificial ingredients.</span>
              </div>
            </div>
            <div>
              form
            </div>
          </div>
        </div>
      </div>

      <Ingredient />
      <Info />
      <Popular />
      <Footer />
    </>
  )
}
