import React from 'react'
import Head from "next/head";
import Image from 'next/image';
import GoTop from '@/components/GoTop'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

import img from "@/assets/hero1.png"

export default function Privacy() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />  
      <GoTop />

      <div className="flex bg-[#f8f3e7] min-h-screen pt-10 pb-10 md:pt-[100px]">
        <div className="flex mx-auto w-11/12 md:w-10/12 bg-white rounded-md shadow border">
          <div className="flex py-10 flex-col space-y-10 mx-auto w-10/12">
            <div>
              <span className="text-3xl md:text-4xl font-bold md:leading-snug ">
                Imagine a community of passionate & ambitious learners, all
                working to make a positive impact on the world around them. Now
                imagine your high school :/
              </span>
            </div>
            <div>
              <span className="text-lg  leading-snug text-gray-700">
                We understand that traditional education is important, but it is
                not enough to prepare you for the real world. That&apos;s why we&apos;ve
                created a full-cycle curriculum that goes beyond the boundaries
                of traditional education, providing you with the hands-on
                experience, mentorship, and support you need to turn your dreams
                into realities.
              </span>
            </div>
            <div>
              <span className="text-lg  leading-snug text-gray-700">
                Our team is dedicated to helping you discover your strengths,
                develop your skills, and build a successful future. Whether
                you&apos;re interested in entrepreneurship, technology, arts, or any
                other field, our program will provide you with the resources,
                guidance, and opportunities you need to make the most of your
                potential.
              </span>
            </div>
            <div>
              <span className="text-lg  leading-snug text-gray-700">
                At Ivy Stat, you will join a community of like-minded
                individuals who share your passion and drive. Together, you will
                learn from mentors and experts, collaborate on projects, and
                build networks that will last a lifetime.
              </span>
            </div>
          </div>
        </div>
      </div>

      <div className="flex flex-col md:flex-row space-y-6 md:space-x-4 bg-white py-10 mx-auto w-11/12">
        <div className="w-full md:w-1/2 flex flex-col space-y-5">
          <span className="text-3xl md:text-4xl font-semibold text-gray-800 md:leading-snug">
            Everything you need to get started with your passion, and nothing
            you don&apos;t need. Ivy Stat bootcamp is the best way for you to do your
            thing.
          </span>
          <div className="flex flex-col space-y-3">
            <div className="flex items-center space-x-3">
              <div className="flex rounded-full shadow border border-gray-100 px-1 py-1 bg-[#ff74be]">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={2}
                  stroke="currentColor"
                  className="w-4 h-4"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M4.5 12.75l6 6 9-13.5"
                  />
                </svg>
              </div>
              <span className="text-sm">
                Online access to job and internship opportunities
              </span>
            </div>
            <div className="flex items-center space-x-3">
              <div className="flex rounded-full shadow border border-gray-100 px-1 py-1 bg-[#ff74be]">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={2}
                  stroke="currentColor"
                  className="w-4 h-4"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M4.5 12.75l6 6 9-13.5"
                  />
                </svg>
              </div>
              <span className="text-sm">
              Flexible scheduling to accommodate schoolwork
              </span>
            </div>
            <div className="flex items-center space-x-3">
              <div className="flex rounded-full shadow border border-gray-100 px-1 py-1 bg-[#ff74be]">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={2}
                  stroke="currentColor"
                  className="w-4 h-4"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M4.5 12.75l6 6 9-13.5"
                  />
                </svg>
              </div>
              <span className="text-sm">
              One-on-one mentorship from network leaders and graduates
              </span>
            </div>
          </div>
        </div>
        <div className='w-full md:w-1/2'>
          <Image src={img} alt="" className='rounded-3xl' />
        </div>
      </div>

      <Footer />  
    </>
  )
}
